import React from "react";
import "./DayTwo.css"
const DayTwo = () =>{
    return(
        <div>
            <nav>
                <a href="#" className="anchor active" >Home</a>
                <a href="#" className= "anchor">About</a>
                <a href="#" className=" anchor">Profile</a>
                <a href="#" className=" anchor">Services</a>
                <a href="#" className=" anchor">Contact</a>
            </nav>
            <div className="section-day-2">
                <h1>This is day-2 content</h1>
                <div className="contents">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi dolor explicabo fugit magnam quisquam? Assumenda eaque exercitationem facere laborum omnis tempora, vitae! Ab amet debitis est ex expedita explicabo, harum magnam, minus nemo nesciunt nisi quae reiciendis! Atque, illo, sunt!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, at aut debitis delectus dolores harum sapiente totam! Cumque, eaque id in itaque nesciunt porro quas quod voluptates? Animi at atque autem beatae deserunt dolore ducimus eius eveniet, hic id laudantium, magnam nam necessitatibus nesciunt officia porro qui quis reprehenderit suscipit tempore temporibus ullam vero vitae. Aperiam aut consequuntur cumque deserunt explicabo, facere fugiat ipsa molestias natus nobis, quibusdam repudiandae voluptates. Atque, dolorem eius eos laborum laudantium non odio quae! Assumenda error fugiat impedit! Animi, architecto assumenda consectetur dicta eaque error facilis incidunt ipsum laboriosam maxime minus nisi quis quo quod, quos repudiandae temporibus ullam ut vel veritatis! Dignissimos dolorum ea est facere, harum ipsum iure laboriosam officiis, porro quasi quibusdam similique tenetur! Adipisci aliquid asperiores aut explicabo modi, nemo nulla perspiciatis quasi quibusdam quos reprehenderit sit sunt, unde. Culpa dicta distinctio eligendi minima officiis, recusandae saepe sequi similique temporibus totam! A amet, aut blanditiis corporis culpa doloremque eaque esse excepturi fuga libero minus molestiae, necessitatibus odio pariatur similique sit veniam. Aliquid, architecto at atque aut autem corporis deserunt dolorem, dolores ea esse ex fuga incidunt ipsum itaque iusto neque nobis non nostrum officiis praesentium qui quidem saepe sit unde vitae.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, at aut debitis delectus dolores harum sapiente totam! Cumque, eaque id in itaque nesciunt porro quas quod voluptates? Animi at atque autem beatae deserunt dolore ducimus eius eveniet, hic id laudantium, magnam nam necessitatibus nesciunt officia porro qui quis reprehenderit suscipit tempore temporibus ullam vero vitae. Aperiam aut consequuntur cumque deserunt explicabo, facere fugiat ipsa molestias natus nobis, quibusdam repudiandae voluptates. Atque, dolorem eius eos laborum laudantium non odio quae! Assumenda error fugiat impedit! Animi, architecto assumenda consectetur dicta eaque error facilis incidunt ipsum laboriosam maxime minus nisi quis quo quod, quos repudiandae temporibus ullam ut vel veritatis! Dignissimos dolorum ea est facere, harum ipsum iure laboriosam officiis, porro quasi quibusdam similique tenetur! Adipisci aliquid asperiores aut explicabo modi, nemo nulla perspiciatis quasi quibusdam quos reprehenderit sit sunt, unde. Culpa dicta distinctio eligendi minima officiis, recusandae saepe sequi similique temporibus totam! A amet, aut blanditiis corporis culpa doloremque eaque esse excepturi fuga libero minus molestiae, necessitatibus odio pariatur similique sit veniam. Aliquid, architecto at atque aut autem corporis deserunt dolorem, dolores ea esse ex fuga incidunt ipsum itaque iusto neque nobis non nostrum officiis praesentium qui quidem saepe sit unde vitae.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, at aut debitis delectus dolores harum sapiente totam! Cumque, eaque id in itaque nesciunt porro quas quod voluptates? Animi at atque autem beatae deserunt dolore ducimus eius eveniet, hic id laudantium, magnam nam necessitatibus nesciunt officia porro qui quis reprehenderit suscipit tempore temporibus ullam vero vitae. Aperiam aut consequuntur cumque deserunt explicabo, facere fugiat ipsa molestias natus nobis, quibusdam repudiandae voluptates. Atque, dolorem eius eos laborum laudantium non odio quae! Assumenda error fugiat impedit! Animi, architecto assumenda consectetur dicta eaque error facilis incidunt ipsum laboriosam maxime minus nisi quis quo quod, quos repudiandae temporibus ullam ut vel veritatis! Dignissimos dolorum ea est facere, harum ipsum iure laboriosam officiis, porro quasi quibusdam similique tenetur! Adipisci aliquid asperiores aut explicabo modi, nemo nulla perspiciatis quasi quibusdam quos reprehenderit sit sunt, unde. Culpa dicta distinctio eligendi minima officiis, recusandae saepe sequi similique temporibus totam! A amet, aut blanditiis corporis culpa doloremque eaque esse excepturi fuga libero minus molestiae, necessitatibus odio pariatur similique sit veniam. Aliquid, architecto at atque aut autem corporis deserunt dolorem, dolores ea esse ex fuga incidunt ipsum itaque iusto neque nobis non nostrum officiis praesentium qui quidem saepe sit unde vitae.</p>
                </div>
            </div>
        </div>
    )
}
export default DayTwo